[build]
  command = "yarn deploy"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUP135kr/pCrA6Vh6TDQS9mTQ3VMpEQvvvy93OiQIrgAb6t2Kch4+s3A/w5eZA4gjxd/UHFj+GDkRHqz/ajmxtrJGWB7BJzui0/aAzNCmiyb6JZ3+Bv/ypmTo1IcYlSyH6uWnqgK0zyvbFNRdT78rGCg6NWQbrbbz9llYpx/z+h3lxI1w2+0GT2ibHPxfq37KuSY+L2d/QQ9WM3MKnSay5jHUsTybichrXN68GeVJUIM6E2mjKcfKo5Sv3o15M0fZQKY3qHIVgV83RLPuTQGRun1QAJsJQVJVdEYc10Mv5tJ0TZvWKdxddIMNeJojh0OjbVsDbC/W0MhQs5N9HJwRTTzwEb5earJdfgf8czl64GUxzlQo5J20BvDT0NB7Nre/YeP69MycpEoxv7bbZF3O0AguG3fLBvcxlutDDYzHjtPO9lzFnnFHGNjOZ3DvUJw5UcbU0Qcx3Aq3OiOJHWVTxM8C0RF6kXZM0w56odFsrFwsQIvPosNn++CEuqIjmNCDZpsU8vJVXNdz2k1aLgQdtqAxgOR3f260nFMUWO01bHXp3lmRe2BA5L5Ssi11n/JOorg5mSoV0rjkzZQ+QcslyO9pXnZgcfJ+E2PxGBa48MD8ZYJlrIN7lIVrd/Nwj2A/AghqlLU4sy9UXmOdOwKrox+suNwuM8Jj3RVulAtuoRQ== Prashant@TECH-PRASHANT.local"
